encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/", views.entry_page, name="entry_page"),
    path("search/", views.search, name="search"),
    path("new_page/", views.new_page, name="new_page"),
    path("edit_page/<str:title>", views.edit_page, name="edit_page"),
    path("random_page/", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class CreateNewPageForm(forms.Form):
    text_input = forms.CharField(label="Text Input",max_length=100)
    textarea_input = forms.CharField(label="", widget=forms.Textarea)

class EditPageForm(forms.Form):
    textarea_input = forms.CharField(label="Textarea Input", widget=forms.Textarea)

encyclopedia/views.py
from django.shortcuts import redirect, render
from random import choice

from . import util
from .forms import CreateNewPageForm, EditPageForm

import markdown2


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry_page(request, title):
    entry = util.get_entry(title)
    if entry:
        html_content = markdown2.markdown(entry)
        return render(request, "encyclopedia/entry_page.html", {
            "html_content": html_content,
            "title": title
        })
    else:
        return render(request, "encyclopedia/not_found.html")

def search(request):
    query = request.GET.get("q")
    print(query)
    if query:
        entry = util.get_entry(query)
        if entry:
            return redirect('wiki:entry_page', title=query)
        
        results = []
        for entry in util.list_entries():
            if query.lower() in entry.lower():
                results.append(entry)
        if results:
            return render(request, "encyclopedia/search_results.html", {
                "results": results,
                "query": query
            })
        
        return render(request, "encyclopedia/results_not_found.html", {
            "query": query
        })
        
def new_page(request):
    if request.method == "POST":
        form = CreateNewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["text_input"]
            content = form.cleaned_data["textarea_input"]

            for entry in util.list_entries():
                if title.lower() == entry.lower():
                    return render(request, "encyclopedia/file_already_exists.html")
            
            util.save_entry(title, content)
            return redirect('wiki:entry_page', title=title)

        else:
            #work on this later
            return 1

    else:
        form = CreateNewPageForm()
    return render(request, "encyclopedia/new_page.html", {
        "form": form
    })

def edit_page(request, title):
    if request.method == "POST":
        form = EditPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["textarea_input"]

            util.save_entry(title, content)
            return redirect("wiki:entry_page", title=title)
    
    content = util.get_entry(title)
    if not content:
        return render(request, "encyclopedia/not_found.html")
    
    form = EditPageForm(initial={"textarea_input": content})
    return render(request, "encyclopedia/edit_page.html", {
            "title": title,
            "form": form
        })

def random_page(request):
    entries = util.list_entries()

    random_entry = choice(entries)
    return redirect("wiki:entry_page", title=random_entry)

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit {{ title }} Page</h1>

    <form method="post" action="{% url 'wiki:edit_page' title=title %}">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div>
        {{ html_content | safe }}
    </div>
    <div>
        <a href="{% url 'wiki:edit_page' title=title %}">Edit Page</a>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/file_already_exists.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    File Already Exists
{% endblock %}

{% block body %}
    <h1 style="color: red;">File Already Exists. Please enter another title.</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry_page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="get">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <form method="post" action="{% url 'wiki:new_page' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Not Found
{% endblock %}

{% block body %}
    <h1 style="color: red;">PAGE NOT FOUND</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/results_not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results Not Found
{% endblock %}

{% block body %}
    <h1 style="color: red;">No results for: "{{ query }}"</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if results%}
        <h1>Results for: {{ query }}</h1>

        <ul>
            {% for entry in results %}
                <li><a href="{% url 'wiki:entry_page' title=entry %}">{{ entry }}</li></a>
            {% endfor %}
        </ul>
    {% else %}
        <h1>No results for: {{ query }}</h1>
    {% endif %}
{% endblock %}